docs_dir: docs/book
site_dir: docs/html
extra:
  project: Queue
  current_version: v1
  versions:
    - v1
nav:
  - Home: index.md
  - v1:
      - Overview: v1/overview.md
      - "Understanding the Queue": v1/what-is-queue.md
      - Server Setup: v1/server-setup.md
      - Installation: v1/installation.md
      - Messenger Configuration: v1/messenger-configuration.md
      - Control Commands: v1/control-commands.md
      - Valkey: v1/valkey.md
      - How to:
          - Communication With Queue: v1/how-to/communication-with-queue.md
          - Send Emails: v1/how-to/send-emails.md
site_name: queue
site_description: "Dotkernel Queue"
repo_url: "https://github.com/dotkernel/queue"
plugins:
  - search
